version: '3.9'

services:
  technical-test-postgres-db:
    image: postgres:16.3
    restart: always
    volumes:
      - "./database/:/var/backup"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass